### ISSUE TITLE
IFT05-Menu>Plan My Leave>Setup Public Holiday

### ISSUE THREAD

**Issue by Annasalihin** [zencomputersystems/eLeave_admin-V3#10]
Need to auto populate (click refresh) the newly added Public Holiday list
Screen Shot : 
![Bugs Image](https://i.ibb.co/FXDxmWD/Screen-Hunter-2576.png)

Assigned to @zenangrl

**Comment by zenangrl** [comment]
After saved new calendar, user can see the updated calendar profile list in Edit.

**Comment by Annasalihin** [comment]
Tested & Verified

Added Successfully label message after user Save New/Edit Calendar
Screen Shot : 
![Bugs Image](https://i.ibb.co/gm7yJt4/Screen-Hunter-2609.png)
