### ISSUE TITLE
IFT13- Employee >Delete function is disabled. 

### ISSUE THREAD

**Issue by Annasalihin** [zencomputersystems/eLeave_admin-V3#18]
Screen Shot : 
![Bugs Image](https://i.ibb.co/Wzz030D/Screen-Hunter-2599.png)

Assigned to @zenangrl

**Comment by zenangrl** [comment]
Only Delete icon is remaining, i will create a drop down for delete icon: 
- active
- inactive
- delete

**Comment by Annasalihin** [comment]
Tested Delete Function.
Deleted Record still displayed after page refresh.
Screen Shot : 
![Bugs Image](https://i.ibb.co/d2KgKfx/Screen-Hunter-2674.png")

**Comment by Annasalihin** [comment]
Tested Delete Function.
Deleted Record still displayed after page refresh.
Screen Shot :

**Comment by Annasalihin** [comment]
Issued closed due to new design has been implemented
