### ISSUE TITLE
Leave Setup > General Leave Policy : Add assigned employee name list under each company

### ISSUE THREAD

**Issue by hananiii** [zencomputersystems/eLeave_admin-V3#49]
Current implementation is only shows assigned employee no. I would be nice if user can see how is assigned under each company

**Comment by steelburn** [comment]
Ni kat page mana Nani?

**Comment by hananiii** [comment]
general leave policy
![Screen Shot 2020-03-20 at 1 25 48 PM](https://user-images.githubusercontent.com/53550715/77138814-646de980-6aae-11ea-8af0-9c9fd2f2a0f8.png)
