### ISSUE TITLE
Findings - Administrator module

### ISSUE THREAD

**Issue by ZCSJC** [zencomputersystems/eLeave_admin-V3#59]
[E-Leave Administrator Module.pptx](https://github.com/zencomputersystems/eLeave_admin-V3/files/4442565/E-Leave.Administrator.Module.pptx)

Pls refer to the attached file.

**Comment by Annasalihin** [comment]
All these issues have been segregated accordingly.Refer Issue #JC01 UNTIL JC06 for reference.
