### ISSUE TITLE
JC03-When edit staff, what is the use of the name list of the left? I need bigger space to key in and view full details of the staff

### ISSUE THREAD

**Issue by Annasalihin** [zencomputersystems/eLeave_admin-V3#62]
![image](https://user-images.githubusercontent.com/43536643/78655456-9e394f80-78f8-11ea-90d5-9e07d1bc4106.png)

**Comment by zenangrl** [comment]
Collapse the side menu to have bigger space.

**Comment by Annasalihin** [comment]
fixed. extend length
![image](https://user-images.githubusercontent.com/43536643/80465048-42993980-896d-11ea-9039-d29a9c32efd4.png)

**Comment by Annasalihin** [comment]
tested & closed
