### ISSUE TITLE
IFT03-Menu>Inbox>Page is under development

### ISSUE THREAD

**Issue by Annasalihin** [zencomputersystems/eLeave_admin-V3#8]
Screen Shot : 
![Bugs Image](https://i.ibb.co/GJ5CyFK/Screen-Hunter-2574.png)

Assigned to @zenangrl

**Comment by zenangrl** [comment]
I have removed the inbox routing since it is not in use at this moment.

**Comment by Annasalihin** [comment]
Tested & Verified
Screen Shot : 
![Bugs Image](https://i.ibb.co/R9wBfpj/Screen-Hunter-2661.png")
